# Generated by Django 2.2 on 2021-04-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('f', 'формируется'), ('pr', 'обрабатывается'), ('p', 'оплачен'), ('r', 'готов'), ('c', 'отменен')], db_index=True, default='f', max_length=1, verbose_name='статус'),
        ),
    ]
